// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/react-mixin/react-mixin.d.ts
declare module "react-mixin" {
    import * as React from 'react';

    namespace reactMixin {
        export interface ClassDecorator {
            <TFunction extends Function>(target: TFunction): TFunction|void;
        }

        interface ReactMixin {
            decorate(mixin: React.Mixin<any, any>): ClassDecorator;
            onClass<S>(clazz: any, mixin: React.Mixin<any, any>): React.ComponentClass<S>;
            <S>(clazz: any, mixin: React.Mixin<any, any>): React.ComponentClass<S>;
        }
    }

    var reactMixin: reactMixin.ReactMixin;

    export = reactMixin;
}
